package com.qf.oa.dao;

import com.qf.oa.entity.Employee;
import com.qf.oa.entity.MyCount;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
            * @mbggenerated
     */
    int updateByPrimaryKey(Employee record);

    List<Employee> queryEmp();

    int addRole(@Param("eid") Integer eid, @Param("rid") Integer[] rid);

    int deleteRole(Integer eid);

    Employee queryByEmail(String email);

    int mentCount();

    int womentCount();

    List<MyCount> queryAllDepNumb();

    List<Employee> excelEmp();
}